definitions:
  models.User:
    properties:
      createdAt:
        type: string
      email:
        type: string
      id:
        type: string
      password:
        type: string
      role_id:
        type: string
      updatedAt:
        type: string
      username:
        type: string
    type: object
  models.UserDto:
    properties:
      email:
        type: string
      password:
        type: string
      role_id:
        type: string
      username:
        type: string
    type: object
info:
  contact: {}
paths:
  /user/new:
    post:
      consumes:
      - application/json
      description: This will create a new user in the system
      parameters:
      - description: Create user
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/models.UserDto'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/models.User'
        "400":
          description: Bad Request
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: Create new user
      tags:
      - users
  /util/health:
    get:
      consumes:
      - application/json
      description: healthcheck
      produces:
      - application/json
      responses: {}
      summary: healthcheck
      tags:
      - util
swagger: "2.0"
